CREATE TABLE t_province_map(
  f_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT '主键',
  f_name VARCHAR(32) NOT NULL COMMENT '名称',
  f_full_name VARCHAR(32) NOT NULL COMMENT '全名称',
  f_code VARCHAR(6) NOT NULL COMMENT '编码',
  f_pin_yin VARCHAR(256) NOT NULL COMMENT '拼音',
  f_operator VARCHAR(32) NOT NULL DEFAULT '' COMMENT '修改人',
  f_update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间'
) COMMENT '省份表, 数据来源于腾讯地图API';

CREATE TABLE t_city_map(
  f_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT '主键',
  f_name VARCHAR(32) NOT NULL COMMENT '名称',
  f_full_name VARCHAR(32) NOT NULL COMMENT '全名称',
  f_code VARCHAR(6) NOT NULL COMMENT '编码',
  f_pin_yin VARCHAR(256) NOT NULL COMMENT '拼音',
  f_operator VARCHAR(32) NOT NULL DEFAULT '' COMMENT '修改人',
  f_update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间'
) COMMENT '城市表, 数据来源于腾讯地图API';

CREATE TABLE t_district_map(
  f_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT '主键',
  f_name VARCHAR(32) NOT NULL COMMENT '名称',
  f_full_name VARCHAR(32) NOT NULL COMMENT '全名称',
  f_code VARCHAR(6) NOT NULL COMMENT '编码',
  f_pin_yin VARCHAR(256) NOT NULL COMMENT '拼音',
  f_operator VARCHAR(32) NOT NULL DEFAULT '' COMMENT '修改人',
  f_update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间'
) COMMENT '县区表, 数据来源于腾讯地图API';