// **********************************************************************
// Parsed By TarsParser(2.4.5), Generated By tars2node(20200707)
// TarsParser Maintained By <TARS> and tars2node Maintained By <superzheng>
// Generated from "Util.tars" by Client Mode
// **********************************************************************

/* eslint-disable */

"use strict";

var TarsStream = require("@tars/stream");
var TarsError  = require("@tars/rpc").error;

var _makeError = function (data, message, type) {
    var error = new Error(message || "");
    error.request = data.request;
    error.response = {
        "costtime" : data.request.costtime
    };
    if (type === TarsError.CLIENT.DECODE_ERROR) {
        error.name = "DECODE_ERROR";
        error.response.error = {
            "code" : type,
            "message" : message
        };
    } else {
        error.name = "RPC_ERROR";
        error.response.error = data.error;
    }
    return error;
};

var Util = Util || {};
module.exports.Util = Util;

Util.CalculateProxy = function () {
    this._name    = undefined;
    this._worker  = undefined;
};

Util.CalculateProxy.prototype.setTimeout = function (iTimeout) {
    this._worker.timeout = iTimeout;
};

Util.CalculateProxy.prototype.getTimeout = function () {
    return this._worker.timeout;
};

Util.CalculateProxy.prototype.setVersion = function (iVersion) {
    this._worker.version = iVersion;
};

Util.CalculateProxy.prototype.getVersion = function () {
    return this._worker.version;
};

var __Util_Calculate$add$IF = {
    "name" : "add",
    "return" : "int32",
    "arguments" : [{
        "name" : "a",
        "class" : "int32",
        "direction" : "in"
    }, {
        "name" : "b",
        "class" : "int32",
        "direction" : "in"
    }, {
        "name" : "c",
        "class" : "int32",
        "direction" : "out"
    }]
};

var __Util_Calculate$add$IE = function (a, b) {
    var os = new TarsStream.TarsOutputStream();
    os.writeInt32(1, a);
    os.writeInt32(2, b);
    return os.getBinBuffer();
};

var __Util_Calculate$add$ID = function (data) {
    try {
        var is = new TarsStream.TarsInputStream(data.response.sBuffer);
        return {
            "request" : data.request,
            "response" : {
                "costtime" : data.request.costtime,
                "return" : is.readInt32(0, true, 0),
                "arguments" : {
                    "c" : is.readInt32(3, true, 0)
                }
            }
        };
    } catch (e) {
        throw _makeError(data, e.message, TarsError.CLIENT.DECODE_ERROR);
    }
};

var __Util_Calculate$add$PE = function (a, b, __$PROTOCOL$VERSION) {
    var tup = new TarsStream.UniAttribute();
    tup.tupVersion = __$PROTOCOL$VERSION;
    tup.writeInt32("a", a);
    tup.writeInt32("b", b);
    return tup;
};

var __Util_Calculate$add$PD = function (data) {
    try {
        var tup = data.response.tup;
        return {
            "request" : data.request,
            "response" : {
                "costtime" : data.request.costtime,
                "return" : tup.readInt32("", 0),
                "arguments" : {
                    "c" : tup.readInt32("c")
                }
            }
        };
    } catch (e) {
        throw _makeError(data, e.message, TarsError.CLIENT.DECODE_ERROR);
    }
};

var __Util_Calculate$add$ER = function (data) {
    throw _makeError(data, "Call Calculate::add failed");
};

Util.CalculateProxy.prototype.add = function (a, b) {
    var version = this._worker.version;
    if (version === TarsStream.Tup.TUP_SIMPLE || version === TarsStream.Tup.TUP_COMPLEX) {
        return this._worker.tup_invoke("add", __Util_Calculate$add$PE(a, b, version), arguments[arguments.length - 1], __Util_Calculate$add$IF).then(__Util_Calculate$add$PD, __Util_Calculate$add$ER);
    } else {
        return this._worker.tars_invoke("add", __Util_Calculate$add$IE(a, b), arguments[arguments.length - 1], __Util_Calculate$add$IF).then(__Util_Calculate$add$ID, __Util_Calculate$add$ER);
    }
};
Util.CalculateProxy.add = __Util_Calculate$add$IF;

var __Util_Calculate$sub$IF = {
    "name" : "sub",
    "return" : "int32",
    "arguments" : [{
        "name" : "a",
        "class" : "int32",
        "direction" : "in"
    }, {
        "name" : "b",
        "class" : "int32",
        "direction" : "in"
    }, {
        "name" : "c",
        "class" : "int32",
        "direction" : "out"
    }]
};

var __Util_Calculate$sub$IE = function (a, b) {
    var os = new TarsStream.TarsOutputStream();
    os.writeInt32(1, a);
    os.writeInt32(2, b);
    return os.getBinBuffer();
};

var __Util_Calculate$sub$ID = function (data) {
    try {
        var is = new TarsStream.TarsInputStream(data.response.sBuffer);
        return {
            "request" : data.request,
            "response" : {
                "costtime" : data.request.costtime,
                "return" : is.readInt32(0, true, 0),
                "arguments" : {
                    "c" : is.readInt32(3, true, 0)
                }
            }
        };
    } catch (e) {
        throw _makeError(data, e.message, TarsError.CLIENT.DECODE_ERROR);
    }
};

var __Util_Calculate$sub$PE = function (a, b, __$PROTOCOL$VERSION) {
    var tup = new TarsStream.UniAttribute();
    tup.tupVersion = __$PROTOCOL$VERSION;
    tup.writeInt32("a", a);
    tup.writeInt32("b", b);
    return tup;
};

var __Util_Calculate$sub$PD = function (data) {
    try {
        var tup = data.response.tup;
        return {
            "request" : data.request,
            "response" : {
                "costtime" : data.request.costtime,
                "return" : tup.readInt32("", 0),
                "arguments" : {
                    "c" : tup.readInt32("c")
                }
            }
        };
    } catch (e) {
        throw _makeError(data, e.message, TarsError.CLIENT.DECODE_ERROR);
    }
};

var __Util_Calculate$sub$ER = function (data) {
    throw _makeError(data, "Call Calculate::sub failed");
};

Util.CalculateProxy.prototype.sub = function (a, b) {
    var version = this._worker.version;
    if (version === TarsStream.Tup.TUP_SIMPLE || version === TarsStream.Tup.TUP_COMPLEX) {
        return this._worker.tup_invoke("sub", __Util_Calculate$sub$PE(a, b, version), arguments[arguments.length - 1], __Util_Calculate$sub$IF).then(__Util_Calculate$sub$PD, __Util_Calculate$sub$ER);
    } else {
        return this._worker.tars_invoke("sub", __Util_Calculate$sub$IE(a, b), arguments[arguments.length - 1], __Util_Calculate$sub$IF).then(__Util_Calculate$sub$ID, __Util_Calculate$sub$ER);
    }
};
Util.CalculateProxy.sub = __Util_Calculate$sub$IF;



